# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edication', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TableName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='tabledocument',
            name='people_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.TableName'),
        ),
    ]
