# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TableDocument',
            new_name='Document',
        ),
        migrations.RenameModel(
            old_name='TableName',
            new_name='People',
        ),
    ]
